name: SAP Tools
version: "4.3.5"
slug: simple_hello_world
description: SAP GUID converter and deep link generator for ByD objects
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: manual
init: false
ingress: true
ingress_port: 3000
panel_icon: mdi:briefcase
panel_title: SAP Tools
panel_admin: false
options:
  dev_domain: dev-tenant.crm.ondemand.com
  acc_domain: acc-tenant.crm.ondemand.com
  prd_domain: prd-tenant.crm.ondemand.com
schema:
  dev_domain: str
  acc_domain: str
  prd_domain: str
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.19"
  amd64: "ghcr.io/home-assistant/amd64-base:3.19"
  armhf: "ghcr.io/home-assistant/armhf-base:3.19"
  armv7: "ghcr.io/home-assistant/armv7-base:3.19"
  i386: "ghcr.io/home-assistant/i386-base:3.19"
